# Generated by Django 4.1 on 2022-08-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('game_mode', models.CharField(max_length=10)),
                ('duration', models.DateField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
                ('rank', models.CharField(max_length=10)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotaApi.match')),
            ],
        ),
    ]
