# Generated by Django 4.1 on 2022-08-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotaApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
